# Numpy Advance - 2

In [1]:
import numpy as np

In [3]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [4]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [1, 1, 1]], dtype=int32)

In [5]:
arr2

array([[1, 1, 2],
       [1, 2, 1],
       [2, 2, 2]], dtype=int32)

#### Flatten the array
Return a copy of array collapsed into one dimension

In [8]:
arr1.flatten()

array([1, 2, 2, 2, 1, 2, 1, 1, 1], dtype=int32)

#### Expand Dimension
syntax >> np.expand(arr_name, 0/1)
- Increase the dimension by 1 in the provided axis, 0 means rows( x- axis) and 1 means columns(y-axis)

In [10]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [11]:
arr.ndim

1

In [ ]:
np.expand_dims(arr, 0)

array([[1, 2, 3, 4]])

In [14]:
np.expand_dims(arr, 1)

array([[1],
       [2],
       [3],
       [4]])

In [15]:
arr = np.random.randint(2, 7, (3, 3))

In [ ]:
np.expand_dims(arr, 0) #=> 1 X 3 X 3
# This means you now have 1 "block" of a 3x3 array.

array([[[2, 2, 6],
        [6, 5, 6],
        [6, 2, 5]]], dtype=int32)

In [ ]:
np.expand_dims(arr, 1)  #=> 1 X 3 X 3
# you now have 3 "blocks", where each block is a 1x3 array (1 row and 3 columns).

array([[[2, 2, 6]],

       [[6, 5, 6]],

       [[6, 2, 5]]], dtype=int32)

### Squeezing by 1 dimension 

In [23]:
arr = np.array([[1], [2], [3]])
arr.squeeze().squeeze() # removes axis of length one from arr 

array([1, 2, 3])

In [26]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [27]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [28]:
arr = np.random.randint(2, 8, (3, 3))
np.repeat(arr, 2)

array([7, 7, 3, 3, 4, 4, 2, 2, 7, 7, 6, 6, 4, 4, 7, 7, 3, 3], dtype=int32)

In [29]:
arr

array([[7, 3, 4],
       [2, 7, 6],
       [4, 7, 3]], dtype=int32)

In [30]:
np.repeat(arr, 2, axis=0)

array([[7, 3, 4],
       [7, 3, 4],
       [2, 7, 6],
       [2, 7, 6],
       [4, 7, 3],
       [4, 7, 3]], dtype=int32)

In [31]:
np.repeat(arr, 2, axis=1)

array([[7, 7, 3, 3, 4, 4],
       [2, 2, 7, 7, 6, 6],
       [4, 4, 7, 7, 3, 3]], dtype=int32)

In [40]:
arr = np.array([[1], [2], [3]])
arr

array([[1],
       [2],
       [3]])

In [38]:
np.roll(arr, shift=1)

array([[3],
       [1],
       [2]])

In [41]:
np.roll(arr, shift=-1)

array([[2],
       [3],
       [1]])

In [43]:
np.roll(arr, -2)

array([[3],
       [1],
       [2]])

In [44]:
c = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [46]:
np.roll(c, shift = -1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [47]:
np.roll(c, shift = 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [48]:
np.roll(c, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

### Operation on numpy string array

In [49]:
d = np.array(["Mritunjay", "Kumar"])
d

array(['Mritunjay', 'Kumar'], dtype='<U9')

In [50]:
np.char.upper(d)

array(['MRITUNJAY', 'KUMAR'], dtype='<U9')

### Trigonometrical function

In [52]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [53]:
np.sin(arr)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825]])

In [54]:
np.cos(arr)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003]])

In [55]:
np.tan(arr)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128],
       [-3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146]])

In [56]:
np.log10(arr)

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999],
       [0.69897   , 0.77815125],
       [0.84509804, 0.90308999]])

In [57]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03]])

In [58]:
np.power(arr, 2)

array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [60]:
np.max(arr)

np.int64(8)

In [61]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [62]:
np.mean(arr)

np.float64(4.5)

In [63]:
np.min(arr)

np.int64(1)

In [64]:
np.std(arr)

np.float64(2.29128784747792)

In [65]:
np.subtract(arr1, arr2)

array([[ 0,  1,  0],
       [ 1, -1,  1],
       [-1, -1, -1]], dtype=int32)

In [66]:
np.multiply(arr1, arr2)

array([[1, 2, 4],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [67]:
np.mod(arr1, arr2) #Return element wise remainder

array([[0, 0, 0],
       [0, 1, 0],
       [1, 1, 1]], dtype=int32)

In [68]:
np.sqrt(arr)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

### Sorting and searching in numpy array


In [69]:
e = np.array([1, 6, 3, 4, 5, 2])
e

array([1, 6, 3, 4, 5, 2])

In [70]:
np.sort(e)

array([1, 2, 3, 4, 5, 6])

In [71]:
f = np.array([[5, 123, 6, 78, 5], [5, 98, 45, 76, 7]])
np.sort(f)

array([[  5,   5,   6,  78, 123],
       [  5,   7,  45,  76,  98]])

In [ ]:
# Find indices where elements should be inserted to maintain order
# np.searchsorted() operates on a 1D array and searches
# for the index where elements should be inserted to maintain order.
f = np.array([1, 2, 3, 4, 5, 7, 8, 9])
np.searchsorted(f, 6)

np.int64(5)

In [ ]:
# count zeros in array
arr = np.array([0, 2, 5, 0, 4, 3, 0, 0, 0, 0, 6])

len(arr) - np.count_nonzero(arr)

6

In [ ]:
np.where(arr>0) # same as above condition

(array([ 1,  2,  4,  5, 10]),)

In [81]:
np.extract(arr>0, arr)

array([2, 5, 4, 3, 6])

In [83]:
arr.byteswap() #Swap the bytes of the array elements

array([                 0, 144115188075855872, 360287970189639680,
                        0, 288230376151711744, 216172782113783808,
                        0,                  0,                  0,
                        0, 432345564227567616])

### Submodule of numpy Matlib

In [86]:
import numpy.matlib as nm

nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [88]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Numpy linear algebra (optional)

In [89]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [1, 1, 1]], dtype=int32)

In [90]:
arr2

array([[1, 1, 2],
       [1, 2, 1],
       [2, 2, 2]], dtype=int32)

In [92]:
arr1 @ arr2

array([[7, 9, 8],
       [7, 8, 9],
       [4, 5, 5]], dtype=int32)

In [93]:
np.linalg.det(arr1)

np.float64(0.9999999999999996)

In [94]:
np.linalg.det(arr2)

np.float64(-2.0)

In [95]:
# In Matrix you cannot divide by another matrix, you have inverse fro this
np.linalg.inv(arr1) 

array([[-1.00000000e+00, -3.33066907e-16,  2.00000000e+00],
       [-1.48029737e-16, -1.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00, -3.00000000e+00]])

You can solve this system of equations using NumPy's linalg.solve() method. Here's how:

## Given equations:
1. 7x + 5.3y - 3z = 2
2. 2x + 3y - 2z = 3
3. 3x + 5y - 3z = 2



In [97]:
A = np.array([[7, 5.3, -3], [2, 3, -2], [3, 5, -3]])
B = np.array([2, 3, 2])

np.linalg.solve(A, B)

array([ 0.375, -5.   , -8.625])