# ***NUMPY***

### 🟢 NumPy Overview

#### 📌 What is NumPy?
NumPy stands for **Numerical Python**. It is a powerful library for numerical computing in Python, designed to handle large, multi-dimensional arrays and matrices efficiently.

#### 📅 History of NumPy
- **Developed in:** 2005 by **Travis Oliphant**
- **Why was it created?**
  - Before 2005, there were special mathematical tools (similar to **Tora** and **Linga**), but they were slow and inefficient.
  - Libraries like **Numeric** and **Numarray** existed but had limitations in speed and functionality.
  - **NumPy** was developed as a fusion of these libraries, providing a fast and optimized array-handling capability.

#### ⚡ Key Features of NumPy
- Supports **multi-dimensional arrays (ndarrays)**.
- Offers **mathematical and statistical functions**.
- Enables **broadcasting** for element-wise operations.
- Provides tools for **linear algebra, Fourier transforms, and random number generation**.
- Efficient memory usage and high performance due to **C-based implementation**.

🚀 **NumPy revolutionized numerical computing by offering optimized array computations, making Python a strong choice for scientific computing and machine learning!**

In [1]:
import numpy as np # I want this official library to called as np

In [2]:
np.__version__

'2.0.1'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
lis = [1, 2, 3, 4, 5, "Mritunjay", 3+5j, True]
type(lis) # It stores hetrogeneous element

list

### 🟢 NumPy Arrays Explained

#### 📌 What is a NumPy Array?
- NumPy stores data in a **NumPy array**.
- An **array** is a data structure that holds elements of the **same data type** (homogeneous data).
- Unlike Python lists, NumPy arrays provide **faster** and **more efficient** operations.

#### ❓ Why Use NumPy Instead of Lists?
1. **Performance:**
   - NumPy is built using **C**, making computations significantly faster than Python lists.
   - Python lists store objects individually, while NumPy arrays store data in a **continuous memory location**, reducing overhead.
   
2. **Efficient Memory Usage:**
   - Since NumPy arrays store only homogeneous data, they require less memory.
   - Operations on large datasets are optimized for speed.

3. **Vectorized Operations:**
   - NumPy supports **vectorized operations**, meaning computations are applied to entire arrays without loops.
   - This leads to concise and readable code.

🚀 **NumPy arrays are the backbone of numerical computing in Python, making data processing efficient and scalable!**

In [12]:
# How to make a numpy array?
l = [1, 2, 3, 4, 5]
# Numpy array is homogeneous >> All elements should be of same datatype

In [10]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr) #ndarray >> nd stands for n-dimensional array

numpy.ndarray

In [11]:
l = [1, 2, 3, 4, "Mritunjay"]
np.array(l)

array(['1', '2', '3', '4', 'Mritunjay'], dtype='<U21')

In [14]:
l = [1, 2, 3, 4, 2.4]
arr = np.array(l)

In [15]:
type(arr)

numpy.ndarray

#### arr.ndim >> It will give what is the dimension of array

In [17]:
arr.ndim # arr has only rows

1

In [19]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr1.ndim

2

### Matrix

In [26]:
mat = np.matrix([1, 2, 3, 4]) # Matrix is a specialized array of 2 dimension

In [27]:
mat.ndim

2

In [28]:
type(mat)

numpy.matrix

In [30]:
mat # To see the number of dimension see the number of opening/closing square bracket []-one, [[]]-two, [[[]]]-three

matrix([[1, 2, 3, 4]])

In [33]:
np.matrix([[[1, 2], [1, 5], [3, 6]]])
# We canot create matrix with 3 dimension it is built-in 2 dimension

ValueError: matrix must be 2-dimensional

In [34]:
np.array([[[1, 2], [1, 5], [3, 6]]])

array([[[1, 2],
        [1, 5],
        [3, 6]]])

### More ways to create an array

In [36]:
l = [1, 2, 3]
l2 = np.asarray(l) # 2nd way -> in initial day It was the only way to create array,
# after this np.array(l) comes into picture

l1 = np.array(l) # 1st way
l3 = np.asanyarray(l)
l3

array([1, 2, 3])

In [41]:
mat

matrix([[1, 2, 3, 4]])

In [ ]:
# asanyarray will convert the input to an ndarray, 
# but pass ndarry subclass through
# but if something is already an array or part of array it will simply allow t pass through it
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [43]:
t = (1, 2, 3, 4, 5, 6)
type(t)

tuple

In [47]:
arr = np.array(t)
arr

array([1, 2, 3, 4, 5, 6])

### Accessing elements of the array

In [48]:
arr[0]

np.int64(1)

In [49]:
#Array is mutable
arr[0] = 12
arr

array([12,  2,  3,  4,  5,  6])

### Shallow Copy

In [52]:
a = arr # a and arr will point to same memory location, so if there is any changes it will reflect on both
a [2] = 457
a

array([ 12,   2, 457,   4,   5,   6])

In [53]:
arr

array([ 12,   2, 457,   4,   5,   6])

### DEEP Copy

In [ ]:
b =arr.copy() #Change in one array will not reflect to other array
b

array([ 12,   2, 457,   4,   5,   6])

In [57]:
b[2] = 34
b

array([12,  2, 34,  4,  5,  6])

In [58]:
arr

array([ 12,   2, 457,   4,   5,   6])

To create an array >> np.array, np.asarray, np.asanyarray

### Multiple approaches to generate any array

In [60]:
# Construct an array by executing a function over each coordinate
arr1 = np.fromfunction(lambda i, j: i==j, (3, 3))
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [61]:
arr1.ndim

2

In [63]:
arr1.shape #It will give you shape of array

(3, 3)

In [66]:
arr1.size #Number of elements in array

9

In [68]:
arr2 = np.fromfunction(lambda i, j : i*j, (3, 3))
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [69]:
arr2.shape

(3, 3)

In [70]:
arr2.ndim

2

In [71]:
arr2.size

9

In [73]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [74]:
for i in range(5):
    print(i)

0
1
2
3
4


In [76]:
(i for i in range(5))

<generator object <genexpr> at 0x0000024CD5F69180>

### We can take help from generator object to create numpy array

In [81]:
iterator = (i for i in range(5))
np.fromiter(iterator, int)

array([0, 1, 2, 3, 4])

In [89]:
np.fromstring("22 23 24 25", sep=" ") # By default dtype is float

array([22., 23., 24., 25.])

In [90]:
np.fromstring("22 23 24 25", sep=" ", dtype=int)
# Value inside a string should be numerical else it will raise ValueError

array([22, 23, 24, 25])

In [91]:
# For string character you have to use split
string = "Mritunjay Kumar Thakur"
string.split(sep=" ")

['Mritunjay', 'Kumar', 'Thakur']

In [92]:
np.array(string.split(" "))

array(['Mritunjay', 'Kumar', 'Thakur'], dtype='<U9')

### Another method of numpy to generate sequence of number

In [95]:
# arange returns returned evenly specified values withing a given interval
np.arange(1, 10) # By default step is 1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.arange(1, 10, 0.7)

array([1. , 1.7, 2.4, 3.1, 3.8, 4.5, 5.2, 5.9, 6.6, 7.3, 8. , 8.7, 9.4])

### give me 10 number between 1 and 5 equally distant

In [98]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])