## Numpy Advance - 1

In [2]:
import numpy as np

In [5]:
np.zeros(10) # Return a new array of given shape and type, filled with zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
a = np.zeros(10, int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.zeros((3, 4), int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((2, 3), int)

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
np.twos(2) #doesn't exist in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [15]:
# If in mathmatical calculation I required it
np.array([[2, 2, 2, 2], [2, 2, 2, 2]])

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [16]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
arr.ndim

2

### Can I create a 3d Array?

In [ ]:
# 3 dimensional array
np.zeros(3) #--> 1d

array([0., 0., 0.])

In [19]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr = np.array((2, 3, 4)) # 3 rows, 4 columns of 2d array with outer dimension of 2

In [25]:
arr.ndim

1

### Can we add more dimensions? 
yes we can add 

In [29]:
a =np.zeros((2, 3, 4, 5))
np.zeros((2, 3, 4, 5))

# 2      3      4      5
# 4th    3rd    2nd    1st -> dimension


array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [30]:
a.ndim

4

In [32]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Adding 5 in all element in all 2-d array

In [33]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [34]:
a = arr+5

In [35]:
a*2

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [36]:
b = a*2

In [37]:
b - 1

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

### All the elements in  the digonal is 1 else where 0.

In [39]:
np.eye(3) # Return a 2-D array with ones on the diagonal and zeros elsewhere.
# Same as identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [9]:
np.empty((3, 4)) 
# Return a new array of given shape and type, without initializing entries.
# It means entries in the array can be any random values.

array([[1.42600232e-311, 6.95320784e-310, 4.92089383e-321,
                    nan],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        1.11253693e-308]])

### Optional

In [14]:
# RandomModule
import random
t= (1, 2, 3, 4, 5, 6)
random.choice(t)

4

In [15]:
random.choice("Mritunjay")

't'

In [19]:
random.randrange(1, 10) 

7

In [22]:
random.random()
# A random no. generated between 0(included) and 1 excluded

0.12534142680750426

In [28]:
lis = [1, 2, 3, 4, 5, 6]
random.shuffle(lis)
print(lis)

[2, 6, 3, 4, 1, 5]


### Uniform Distribution

In [31]:
random.uniform(7, 14) 
# Where probability of getting all the data point is equual

11.917891647166481

### Random numbers related concept in numpy

In [33]:
np.random.random_sample()

0.9954090345239213

In [34]:
np. random.random_sample((5,))
#1 dim array of 5 random no 

array([0.44236824, 0.13878988, 0.77736271, 0.45508353, 0.56281738])

In [36]:
np.random.rand(1)

array([0.00754662])

In [37]:
np.random.rand(2, 3)

array([[0.55382601, 0.91351062, 0.55098339],
       [0.98523642, 0.05953053, 0.13046694]])

In [38]:
np.random.randn(2, 3)
# Return a sample (or samples) from the stndard normal distributation

array([[-0.79693782,  0.79465234,  1.19730189],
       [-1.49431834,  0.81710497,  0.08778617]])

In [40]:
np.random.randint(1, 5, size=(3, 4)) #start from 1 and end at 5(excluded) and give array of size (3, 4)

array([[2, 1, 1, 4],
       [2, 3, 3, 1],
       [1, 4, 3, 2]], dtype=int32)

In [42]:
arr = np.random.randint(1, 5, size=(4, 5))
arr.ndim

2

In [43]:
arr.shape

(4, 5)

In [44]:
arr.size

20

In [45]:
arr

array([[3, 2, 4, 4, 2],
       [1, 3, 2, 4, 2],
       [4, 1, 2, 4, 3],
       [1, 1, 3, 3, 2]], dtype=int32)

#### Reshaping of array >> 
Returns the data containing the same data with a new shape. Array size will never change, always reshape parameter should be multiplication of original array size

In [47]:
arr1 = arr.reshape(2, 10) 
arr1

array([[3, 2, 4, 4, 2, 1, 3, 2, 4, 2],
       [4, 1, 2, 4, 3, 1, 1, 3, 3, 2]], dtype=int32)

In [48]:
arr.size

20

In [49]:
arr1.size

20

In [50]:
arr.reshape(4, 4)

ValueError: cannot reshape array of size 20 into shape (4,4)

In [53]:
# cSE : when you don't know in reshape, what should be the row or column count
# use any negative value for rows or columns
arr.reshape(4, -1)

array([[3, 2, 4, 4, 2],
       [1, 3, 2, 4, 2],
       [4, 1, 2, 4, 3],
       [1, 1, 3, 3, 2]], dtype=int32)

In [55]:
arr.reshape(-10, 5)

array([[3, 2, 4, 4, 2],
       [1, 3, 2, 4, 2],
       [4, 1, 2, 4, 3],
       [1, 1, 3, 3, 2]], dtype=int32)

In [57]:
arr.reshape(10, -5).base

array([[3, 2, 4, 4, 2],
       [1, 3, 2, 4, 2],
       [4, 1, 2, 4, 3],
       [1, 1, 3, 3, 2]], dtype=int32)

In [59]:
arr.reshape(2, 2, 5) # multiplication should be equal to array size
# 2 X 2 X 5 ka 3d array

array([[[3, 2, 4, 4, 2],
        [1, 3, 2, 4, 2]],

       [[4, 1, 2, 4, 3],
        [1, 1, 3, 3, 2]]], dtype=int32)

In [60]:
arr.reshape(2, 1, 2, 5).ndim

4

### Conditions on array


In [69]:
arr = np.random.randint(1, 10, (5, 6))

In [70]:
arr.shape

(5, 6)

In [71]:
arr.size

30

In [72]:
arr.ndim

2

In [73]:
# Want to check which element is greater then certain value
arr > 3

array([[False,  True, False,  True,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False,  True, False,  True,  True,  True]])

In [74]:
arr[arr > 3]

array([9, 5, 6, 8, 9, 6, 6, 8, 5, 8, 5, 5, 6, 8, 8, 9, 7, 7, 7, 9, 9, 9,
       5], dtype=int32)

In [75]:
arr[arr<3]

array([1, 2, 2, 2], dtype=int32)

In [77]:
# To access elements in an array
arr[1]

array([9, 3, 6, 6, 8, 5], dtype=int32)

In [79]:
arr[1][2]

np.int32(6)

In [81]:
arr

array([[3, 9, 3, 5, 6, 8],
       [9, 3, 6, 6, 8, 5],
       [1, 2, 8, 5, 5, 6],
       [8, 8, 9, 7, 7, 7],
       [2, 9, 2, 9, 9, 5]], dtype=int32)

## Slicing in Matrix
slicing is Selects a subarray (continuous elements)
#### syntax >>
*****arr[row_start:row_end, column_start:column_end]*****


In [80]:
arr[:2]

array([[3, 9, 3, 5, 6, 8],
       [9, 3, 6, 6, 8, 5]], dtype=int32)

In [83]:
# from 0th row to 2nd row
arr[0 : 3]

array([[3, 9, 3, 5, 6, 8],
       [9, 3, 6, 6, 8, 5],
       [1, 2, 8, 5, 5, 6]], dtype=int32)

In [87]:
# I want 0th column and 2nd column but only upto 2nd row
arr[0:3, [0, 2]]

array([[3, 3],
       [9, 6],
       [1, 8]], dtype=int32)

In [90]:
# slicing on both rows and columns together
arr[0:3, [1, 3]]

array([[9, 5],
       [3, 6],
       [2, 5]], dtype=int32)

In [91]:
# arr[row_start:row_end, column_start:column_end]
arr[0:3, 1:3]

array([[9, 3],
       [3, 6],
       [2, 8]], dtype=int32)

In [95]:
arr

array([[3, 9, 3, 5, 6, 8],
       [9, 3, 6, 6, 8, 5],
       [1, 2, 8, 5, 5, 6],
       [8, 8, 9, 7, 7, 7],
       [2, 9, 2, 9, 9, 5]], dtype=int32)

## Advanced indexing (arr[[row1, row2], [col1, col2]]) picks specific elements, not subarrays.

- This does not select rows 0 & 2 and columns 3 & 4 as you expected.
- Instead, it performs advanced indexing, which selects elements at (0,3) and (2,4).

In [94]:
arr[[0, 2], [3, 4]]

array([5, 5], dtype=int32)

In [96]:
# arr[row_start:row_end, column_start:column_end]
arr[[0, 1], 2:3]

array([[3],
       [6]], dtype=int32)

### Mathematical operation on two arrays

In [97]:
arr1 = np.random.randint(2, 6, (3, 4))
arr2 = np.random.randint(1, 7, (3, 4))

In [98]:
arr1

array([[2, 5, 3, 3],
       [5, 3, 5, 2],
       [2, 3, 2, 5]], dtype=int32)

In [99]:
arr2

array([[3, 5, 2, 6],
       [5, 4, 5, 1],
       [4, 4, 2, 2]], dtype=int32)

In [102]:
# adding array indexwise
arr1+arr2

array([[ 5, 10,  5,  9],
       [10,  7, 10,  3],
       [ 6,  7,  4,  7]], dtype=int32)

In [103]:
#indexwise array substraction
arr1-arr2

array([[-1,  0,  1, -3],
       [ 0, -1,  0,  1],
       [-2, -1,  0,  3]], dtype=int32)

In [104]:
#indexwise array multiplication, not matrix multiplication
arr1*arr2

array([[ 6, 25,  6, 18],
       [25, 12, 25,  2],
       [ 8, 12,  4, 10]], dtype=int32)

In [105]:
#indexwise array division
arr1/arr2

array([[0.66666667, 1.        , 1.5       , 0.5       ],
       [1.        , 0.75      , 1.        , 2.        ],
       [0.5       , 0.75      , 1.        , 2.5       ]])

### Matrix Multiplication >>
Matrix is a specialized 2d array, Matrix multiplication is diffrent then index wise multiplication

### Matrix Multiplication Condition

Matrix multiplication is valid if the **columns** of the first matrix equal the **rows** of the second.

- **A (m×n)** and **B (n×p)** → Valid if **n = n**
- Resulting matrix: **(m×p)**

#### Example:
✅ `A (2×3) × B (3×4) → C (2×4)`
❌ `A (2×3) × B (2×4) → Not possible (3 ≠ 2)`



In [107]:
arr1 = np.random.randint(3, 6, (3, 3))
arr2 = np.random.randint(3, 6, (3, 3))

In [108]:
arr1 @ arr2 # >> Matrix multiplication

array([[49, 51, 56],
       [42, 50, 53],
       [50, 57, 61]], dtype=int32)

In [109]:
arr1 * arr2 # >> Index wise array multiplication

array([[25, 12, 16],
       [ 9, 16, 20],
       [12, 25, 25]], dtype=int32)

In [110]:
# Another method for matrix multiplication
np.dot(arr1, arr2)

array([[49, 51, 56],
       [42, 50, 53],
       [50, 57, 61]], dtype=int32)

In [111]:
# a X b @ b X c ===>  resultantr => a X c

## Broadcasting in NumPy

Broadcasting expands smaller arrays to match larger ones for efficient operations.

### Example: `arr + [1, 2, 3]`
```python
import numpy as np

arr = np.zeros((3, 3))
b = np.array([1, 2, 3])
result = arr + b  
```
#### **Result:**
```
[[1 2 3]
 [1 2 3]
 [1 2 3]]
```
### **Key Benefits:**
- No need for manual reshaping
- Saves memory
- Enables efficient computations



In [113]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [114]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [115]:
arr + np.array([1, 2, 3, 4])

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

## Transpose of matrix
Converting rows to columns and columns to rows. It will work for 2-d data 

In [121]:
a = np.array([[1, 2, 3, 4], [4, 3, 2, 1]])
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [124]:
a.T

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])